import type { WalletScanResult } from '@wallet-health/types';
import { formatAddress } from './utils';

export function exportAsJSON(scanResult: WalletScanResult) {
  const dataStr = JSON.stringify(scanResult, null, 2);
  const dataBlob = new Blob([dataStr], { type: 'application/json' });
  const url = URL.createObjectURL(dataBlob);
  const link = document.createElement('a');
  link.href = url;
  link.download = `wallet-health-report-${formatAddress(scanResult.address)}-${Date.now()}.json`;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}

export function exportAsCSV(scanResult: WalletScanResult) {
  // Create CSV content
  let csv = 'Wallet Health Report\n\n';
  csv += `Wallet Address,${scanResult.address}\n`;
  csv += `Chain ID,${scanResult.chainId}\n`;
  csv += `Security Score,${scanResult.score}/100\n`;
  csv += `Risk Level,${scanResult.riskLevel}\n`;
  csv += `Scan Date,${new Date(scanResult.timestamp).toLocaleString()}\n\n`;

  // Token Approvals Section
  csv += 'Token Approvals\n';
  csv += 'Token Symbol,Token Address,Spender Address,Allowance,Is Unlimited,Is Risky\n';
  scanResult.approvals.forEach((approval) => {
    csv += `${approval.tokenSymbol},${approval.token},${approval.spender},${approval.allowance},${approval.isUnlimited},${approval.isRisky}\n`;
  });
  csv += '\n';

  // Risk Alerts Section
  csv += 'Risk Alerts\n';
  csv += 'Severity,Title,Description\n';
  scanResult.alerts.forEach((alert) => {
    csv += `${alert.severity},${alert.title},"${alert.description}"\n`;
  });

  // Create and download
  const dataBlob = new Blob([csv], { type: 'text/csv' });
  const url = URL.createObjectURL(dataBlob);
  const link = document.createElement('a');
  link.href = url;
  link.download = `wallet-health-report-${formatAddress(scanResult.address)}-${Date.now()}.csv`;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}

export function generateReportText(scanResult: WalletScanResult): string {
  let report = '═══════════════════════════════════════\n';
  report += '    WALLET HEALTH MONITOR REPORT\n';
  report += '═══════════════════════════════════════\n\n';
  
  report += `Wallet Address: ${scanResult.address}\n`;
  report += `Chain ID: ${scanResult.chainId}\n`;
  report += `Scan Date: ${new Date(scanResult.timestamp).toLocaleString()}\n\n`;
  
  report += '─────────────────────────────────────\n';
  report += '  SECURITY SCORE\n';
  report += '─────────────────────────────────────\n';
  report += `Score: ${scanResult.score}/100\n`;
  report += `Risk Level: ${scanResult.riskLevel.toUpperCase()}\n\n`;
  
  if (scanResult.alerts.length > 0) {
    report += '─────────────────────────────────────\n';
    report += '  RISK ALERTS\n';
    report += '─────────────────────────────────────\n';
    scanResult.alerts.forEach((alert, index) => {
      report += `\n${index + 1}. ${alert.title}\n`;
      report += `   Severity: ${alert.severity.toUpperCase()}\n`;
      report += `   ${alert.description}\n`;
    });
    report += '\n';
  }
  
  if (scanResult.approvals.length > 0) {
    report += '─────────────────────────────────────\n';
    report += '  TOKEN APPROVALS\n';
    report += '─────────────────────────────────────\n';
    report += `Total Active Approvals: ${scanResult.approvals.length}\n\n`;
    
    const riskyApprovals = scanResult.approvals.filter(a => a.isRisky || a.isUnlimited);
    if (riskyApprovals.length > 0) {
      report += `⚠️ Risky Approvals: ${riskyApprovals.length}\n`;
      riskyApprovals.forEach((approval) => {
        report += `  - ${approval.tokenSymbol}: ${formatAddress(approval.spender)}`;
        if (approval.isUnlimited) report += ' (UNLIMITED)';
        report += '\n';
      });
    }
    report += '\n';
  }
  
  report += '─────────────────────────────────────\n';
  report += `Generated by Wallet Health Monitor\n`;
  report += `https://wallet-health.app\n`;
  report += '═══════════════════════════════════════\n';
  
  return report;
}

export function copyToClipboard(scanResult: WalletScanResult) {
  const reportText = generateReportText(scanResult);
  
  if (navigator.clipboard && navigator.clipboard.writeText) {
    navigator.clipboard.writeText(reportText).then(
      () => {
        console.log('Report copied to clipboard');
      },
      (err) => {
        console.error('Failed to copy report:', err);
      }
    );
  } else {
    // Fallback for older browsers
    const textArea = document.createElement('textarea');
    textArea.value = reportText;
    textArea.style.position = 'fixed';
    textArea.style.left = '-999999px';
    document.body.appendChild(textArea);
    textArea.select();
    try {
      document.execCommand('copy');
      console.log('Report copied to clipboard (fallback)');
    } catch (err) {
      console.error('Failed to copy report (fallback):', err);
    }
    document.body.removeChild(textArea);
  }
}

